"""Shared constants for NHL prediction system services."""

# Redis Configuration
REDIS_DEFAULT_URL = "redis://localhost:6379/0"
REDIS_KEY_EXPIRY_SECONDS = 60
REDIS_TEAM_CACHE_EXPIRY_SECONDS = 86400  # 24 hours

# Redis Stream Names
STREAM_EVENTS = "events"
STREAM_FEATURES = "features"
STREAM_PREDICTIONS = "predictions"

# Consumer Group Names
GROUP_FEATURE_STATE = "feature_state"
GROUP_MODEL_SVC = "model_svc"
GROUP_INGESTORS = "ingestors"

# Consumer ID Ranges
CONSUMER_ID_MIN = 1000
CONSUMER_ID_MAX = 9999

# Database Configuration
DATABASE_AUTOCOMMIT = True

# NHL API Configuration
NHL_API_BASE_URL = "https://api-web.nhle.com/v1"
NHL_API_TIMEOUT_SECONDS = 10.0

# Game Configuration
GAME_PERIOD_DURATION_SECONDS = 1200  # 20 minutes
GAME_TOTAL_REGULATION_PERIODS = 3
GAME_TOTAL_REGULATION_TIME_SECONDS = 3600  # 60 minutes
SYNTHETIC_GAME_DURATION_SECONDS = 1200  # 20 minutes for demo

# Event Processing
EVENT_PROCESSING_SLEEP_SECONDS = 0.5  # Synthetic game event emission rate
EVENT_PROCESSING_COUNT = 10  # Number of events to read per batch
EVENT_PROCESSING_BLOCK_MS = 1000  # Redis XREAD block time in milliseconds
NHL_EVENT_INGESTION_SLEEP_SECONDS = 0.01  # Fast ingestion (~100 events/sec)

# Synthetic Event Weights
EVENT_WEIGHT_SHOT = 0.6
EVENT_WEIGHT_FACEOFF = 0.1
EVENT_WEIGHT_HIT = 0.2
EVENT_WEIGHT_PENALTY = 0.1

# Game Probabilities
PROBABILITY_SHOT_IS_GOAL = 0.07
PROBABILITY_POWER_PLAY = 0.08

# Strength Types
STRENGTH_EVEN = "EV"
STRENGTH_POWER_PLAY = "PP"
STRENGTH_PENALTY_KILL = "PK"
STRENGTH_SHORTHANDED = "SH"
STRENGTH_EMPTY_NET = "EN"
STRENGTH_EMPTY_NET_PP = "ENPP"

# Event Types
EVENT_TYPE_GOAL = "GOAL"
EVENT_TYPE_SHOT = "SHOT"
EVENT_TYPE_FACEOFF = "FACEOFF"
EVENT_TYPE_HIT = "HIT"
EVENT_TYPE_PENALTY = "PENALTY"
EVENT_TYPE_BLOCK = "BLOCK"

# NHL API Event Type Codes
NHL_EVENT_PERIOD_START = "520"
NHL_EVENT_STOPPAGE = "516"
NHL_EVENT_PERIOD_END = "517"
NHL_EVENT_GAME_END = "524"
NHL_EVENT_CODE_FACEOFF = 502
NHL_EVENT_CODE_HIT = 503
NHL_EVENT_CODE_GIVEAWAY = 504
NHL_EVENT_CODE_GOAL = 505
NHL_EVENT_CODE_SHOT = 506
NHL_EVENT_CODE_MISSED_SHOT = 507
NHL_EVENT_CODE_BLOCK = 508
NHL_EVENT_CODE_PENALTY = 509

# Rink Coordinates
RINK_X_MIN = -100.0
RINK_X_MAX = 100.0
RINK_Y_MIN = -42.5
RINK_Y_MAX = 42.5

# Prometheus Metrics
PROMETHEUS_PORT = 9000
PROMETHEUS_LATENCY_BUCKETS = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2]

# Win Probability Calculation
WIN_PROB_MIN = 0.05  # Minimum win probability (5%)
WIN_PROB_MAX = 0.95  # Maximum win probability (95%)
WIN_PROB_SCORE_WEIGHT_MIN = 1.2
WIN_PROB_SCORE_WEIGHT_MAX = 2.0
WIN_PROB_TIME_CRITICAL_THRESHOLD_1 = 300  # 5 minutes
WIN_PROB_TIME_CRITICAL_THRESHOLD_2 = 600  # 10 minutes
WIN_PROB_LEAD_MULTIPLIER_LATE = 0.15
WIN_PROB_LEAD_MULTIPLIER_MID = 0.12
WIN_PROB_LEAD_MULTIPLIER_EARLY = 0.10
WIN_PROB_OT_LEAD_Z_SCORE = 3.0

# Situation Code Parsing
SITUATION_CODE_DEFAULT = "1551"  # 5v5 even strength
SITUATION_AWAY_SKATERS_INDEX = 1
SITUATION_HOME_SKATERS_INDEX = 3
SITUATION_NORMAL_SKATERS = 5
SITUATION_EMPTY_NET_SKATERS = 6
SITUATION_GOALIE_PULLED_SKATERS = 0

# Overtime Configuration
PERIOD_OVERTIME = 4
PERIOD_SHOOTOUT = 5

# FastAPI Configuration
CORS_ALLOW_ALL = "*"
CACHE_CONTROL_NO_CACHE = "no-cache, no-store, must-revalidate, max-age=0"

# Model Configuration
MODEL_DEFAULT_ID = "lightgbm_20251104_121934_d9b5b03f"
MODEL_TYPE_BASELINE = "baseline"

# Model Prediction Throttling
MODEL_PREDICTION_INTERVAL_SECONDS = 3.0  # Update predictions every N seconds
MODEL_PREDICTION_MAX_WORKERS = 4  # ThreadPool workers for async inference
MODEL_PREDICTION_CRITICAL_TIME_SECONDS = 300  # Last 5 minutes - predict every event
MODEL_PREDICTION_CLOSE_GAME_THRESHOLD = 1  # Score diff for "close game"

# Significant Events (Always Predict)
SIGNIFICANT_EVENTS = [
    EVENT_TYPE_GOAL,
    EVENT_TYPE_PENALTY,
]

# Conditional Significant Events (Only in close games)
CONDITIONAL_SIGNIFICANT_EVENTS = [
    EVENT_TYPE_SHOT,
    EVENT_TYPE_BLOCK,
]

# Logging
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# Rate Limiting
RATE_LIMIT_REQUESTS = 100  # requests per window
RATE_LIMIT_WINDOW_SECONDS = 60  # 1 minute window

# Health Check
HEALTH_CHECK_TIMEOUT_SECONDS = 5.0

# HTTP Status Codes
HTTP_STATUS_OK = 200
HTTP_STATUS_NO_CONTENT = 204
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_SERVICE_UNAVAILABLE = 503
